name : Experiment

on :
  push :
    branches : [ master ]

jobs :

  Experiment :
    if : "false && !startsWith( github.event.head_commit.message, 'version' )"
    runs-on : ${{ matrix.os }}
    strategy :
      fail-fast  : false
      matrix :
        os : [ ubuntu-latest, windows-latest, macos-latest ]
        node-version : [ 10.x, 12.x, 13.x, 14.x ]
    steps :
    - uses : actions/checkout@v2
    - name : ${{ matrix.node-version }}
      uses : actions/setup-node@v1
      with :
        node-version : ${{ matrix.node-version }}
    - run : npm i
    - run : node proto/wtools/abase/l9.test/consequence/Ext.test.s v:5 s:0 r:timeLimitWaitingEnough
